### ISSUE TITLE
Disable signing

### ISSUE THREAD

**Issue by Daxanius** [Daxanius/NoPryingEyes#10]
A client-side option to disable sending signed messages. Will require to let the client know if a server accepts unsigned messages. Could also be server-side to disable the requirement of signed messages.

**Comment by Madis0** [comment]
> Disable chat reporting using 2 different modes

Can you explain the two modes?

**Comment by Daxanius** [comment]
You can find more information on the modes on Modrinth, though I still have to update the README here.

https://modrinth.com/mod/no-prying-eyes

^ The modes are fully described here.

I'll update the README  in the meantime
