### ISSUE TITLE
Explain "Disable profanity filter"

### ISSUE THREAD

**Issue by Madis0** [Daxanius/NoPryingEyes#18]
What is "Disable profanity filter"?

- Does it refer to the Realms feature and therefore just toggle the option in user's Minecraft profile?
- Does it just change how the chat is displayed so there won't be asterisks, somehow?
- Does it do something else?

**Comment by Daxanius** [comment]
This disables the profanity filter (used in realms) that you can also just disable in your Minecraft account settings. It removes the asterisks. At least on the client-side of things, as I cannot modify realms servers.

It's a nice feature to be able to toggle on the fly without having to potentially go on the Minecraft website, modify your account settings and restarting your game.

About the setting on the account settings, you can only disable that setting if Mojang knows you are 18+, this means children cannot disable this setting in their account settings without the consent / control of a guardian. This feature can basically bypass that.

**Comment by Madis0** [comment]
Thanks for the answer!

**Comment by Daxanius** [comment]
No problem, always a pleasure!
