### ISSUE TITLE
What are the differences between the system used by this mod and the one used by NCR?

### ISSUE THREAD

**Issue by TechPro424** [Daxanius/NoPryingEyes#19]
What are the differences between the "disable chat report" system used by this mod and the one used by [No Chat Reports](https://modrinth.com/mod/no-chat-reports)?

**Comment by Daxanius** [comment]
At it's core? This mod does practically the same as No Chat Reports, with the main difference being customization.

If you have No Chat Reports installed client-side you don't send your public key / don't encrypt messages to servers. No Chat Reports does not allow the option to disable, though this seems to have changed in [this](https://github.com/Aizistral-Studios/No-Chat-Reports/commit/0674c43d012f5aeb019a1df6f9eac6af1f5b2666) recent commit

Besides that, there isn't much difference. It's pick whichever mod you prefer, pick No Chat Reports? That's fine, it's a good mod, I'm not gonna hold you back. Pick No Prying Eyes? That's fine too, it provides some features that I personally would prefer using over No Chat Reports, and thus I will stick with my own mod.

**Comment by Daxanius** [comment]
One thing I should also mention which is a rather big difference is licensing. 

No Chat Reports is licensed under the [WTFPL](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.2-Fabric/LICENSE) license. This means that anyone can do whatever with the code, including making it proprietary.

No Prying Eyes is licensed under the [GPL-3.0](https://github.com/Daxanius/NoPryingEyes/blob/main/LICENSE) license, which means you can *basically* do whatever you want, as long as the code remains open-source and you refer to the original source. 

Is it a big difference to me? No, not really. I just like keeping things open-source.

**Comment by TechPro424** [comment]
Switched to NPE from NCR because open-source better

**Comment by HyperSoop** [comment]
NCR is open source, it's even opener source with abosolutely no restrictions - that's what WTFPL means.

**Comment by Daxanius** [comment]
You make a very good point. I can't really argue with it. But I personally prefer the GPL license since I do not want people to take advantage or profit from my work (which I do not earn a red cent on). While it most certainly is true that WTFPL allows more freedom of use with the code and the likes, it can be used for malicious practices. 

I have been considering switching most of my licenses out for something like MIT or GPLv2, but I don't see myself using WTFPL anytime soon. A part of my upbringing was "never let people take advantage of your work", and I'm staying true to that when writing FOSS.

This is a case of personal preference.

**Comment by Daxanius** [comment]
By taking advantage I mean maliciously. I don't mind people using it in their own hobby projects and the likes of course.

**Comment by HyperSoop** [comment]
> Switched to NPE from NCR because open-source better

yeah i was just replying to this

**Comment by TechPro424** [comment]
> > Switched to NPE from NCR because open-source better
> 
> yeah i was just replying to this

What I meant by "open-source better" was that keeping projects open source using licenses like GPLv3 is better
ik NCR is open source
but yeah I agree that the comment wasn't too clear on that
