### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by TechPro424** [Daxanius/NoPryingEyes#24]
Please update the mod to 1.19.3

**Comment by Daxanius** [comment]
I'll look into it! My apologies I haven't been active lately, college has taken it's toll on me. Are there any other features you'd like to see with the update?

**Comment by TechPro424** [comment]
> Are there any other features you'd like to see with the update?

I have noticed that when joining Aternos servers with NCR installed with default configs, it still gives me the warning toast that chat reporting is enabled on the server, but it actually isn't. Maybe you could look into that?

**Comment by Daxanius** [comment]
That's interesting, I wouldn't know what would cause that behavior. Thanks! I'll look into it :)

**Comment by TechPro424** [comment]
How far has the update come?

**Comment by Daxanius** [comment]
I am currently prioritizing my exams over the mod. Tomorrow should be my last one. In theory the update won't even take a day.

**Comment by TechPro424** [comment]
Understandable, my last one was today :)

**Comment by Daxanius** [comment]
Finally... It happened... 

I updated the mod to 1.19.3! Haha, took me longer than needed but hey.

Just open a new issue if you experience any issue with it.
